baseURL = "http://example.org/"
languageCode = "ja-JP"
title = "Hugo Tutorial Site"
theme = "mytheme"

[Taxonomies]
    tag = "tags"
    archive = "archives"

[related]
    threshold = 50
    includeNewer = true
    toLower = false
    [[related.indices]]
        name = "tags"
        weight = 100